package helper

// import "hospitality-service/domain"

// var (
// 	DefaultGeneral = []domain.GeneralData{
// 		{LanguageID: 1, Type: "greeting_button", Text: "greeting_button"},
// 		{LanguageID: 2, Type: "greeting_button", Text: "greeting_button"},
// 		{LanguageID: 1, Type: "greeting_message", Text: "greeting_message"},
// 		{LanguageID: 2, Type: "greeting_message", Text: "greeting_message"},
// 		{LanguageID: 1, Type: "greeting_sender", Text: "greeting_sender"},
// 		{LanguageID: 2, Type: "greeting_sender", Text: "greeting_sender"},
// 		{LanguageID: 1, Type: "greeting_title", Text: "greeting_title"},
// 		{LanguageID: 2, Type: "greeting_title", Text: "greeting_title"},
// 		{LanguageID: 1, Type: "greeting_valediction", Text: "greeting_valediction"},
// 		{LanguageID: 2, Type: "greeting_valediction", Text: "greeting_valediction"},
// 		{LanguageID: 1, Type: "personalization_description", Text: "personalization_description"},
// 		{LanguageID: 2, Type: "personalization_description", Text: "personalization_description"},
// 		{LanguageID: 1, Type: "personalization_instruction_label", Text: "personalization_instruction_label"},
// 		{LanguageID: 2, Type: "personalization_instruction_label", Text: "personalization_instruction_label"},
// 		{LanguageID: 1, Type: "personalization_name", Text: `[{"name":"Staycation","image":"staycation.svg"}, {"name":"Explore area","image":"explore.svg"}]`},
// 		{LanguageID: 2, Type: "personalization_name", Text: `[{"name":"Staycation","image":"staycation.svg"}, {"name":"Explore area","image":"explore.svg"}]`},
// 		{LanguageID: 1, Type: "personalization_title", Text: "personalization_title"},
// 		{LanguageID: 2, Type: "personalization_title", Text: "personalization_title"},
// 		{LanguageID: 1, Type: "select_language_body", Text: "select_language_body"},
// 		{LanguageID: 2, Type: "select_language_body", Text: "select_language_body"},
// 		{LanguageID: 1, Type: "select_language_navigattor", Text: "select_language_navigattor"},
// 		{LanguageID: 2, Type: "select_language_navigattor", Text: "select_language_navigattor"},
// 		{LanguageID: 1, Type: "select_language_title", Text: "select_language_title"},
// 		{LanguageID: 2, Type: "select_language_title", Text: "select_language_title"},
// 		{LanguageID: 1, Type: "welcome_button", Text: "welcome_button"},
// 		{LanguageID: 1, Type: "welcome_title", Text: "welcome_title"},
// 	}

// 	InitialMenu = []domain.DefaultMenu{
// 		{
// 			OrderID:     1,
// 			Route:       nil,
// 			Icon:        StrPtr("default-menu-home.svg"),
// 			Image:       nil,
// 			Template:    StrPtr("home"),
// 			Description: StrPtr("Home"),
// 			Status:      "active",
// 			Translations: []domain.MenuTranslation{
// 				{LanguageID: 1, Title: "Home", Caption: nil, Description: nil},
// 				{LanguageID: 2, Title: "Beranda", Caption: nil, Description: nil},
// 			},
// 		},
// 		{
// 			OrderID:     2,
// 			Route:       nil,
// 			Icon:        StrPtr("default-menu-channels.svg"),
// 			Image:       nil,
// 			Template:    StrPtr("channel"),
// 			Description: StrPtr("TV channels"),
// 			Status:      "active",
// 			Translations: []domain.MenuTranslation{
// 				{LanguageID: 1, Title: "TV Channels", Caption: nil, Description: nil},
// 				{LanguageID: 2, Title: "Channel TV", Caption: nil, Description: nil},
// 			},
// 		},
// 		{
// 			OrderID:     3,
// 			Route:       nil,
// 			Icon:        StrPtr("default-menu-fundeals.svg"),
// 			Image:       nil,
// 			Template:    StrPtr("menu"),
// 			Description: StrPtr("Fun & Deals"),
// 			Status:      "active",
// 			Translations: []domain.MenuTranslation{
// 				{LanguageID: 1, Title: "Fun & Deals", Caption: StrPtr("Fun & Deals"), Description: nil},
// 				{LanguageID: 2, Title: "Akktivitas Seru", Caption: StrPtr("Akktivitas Seru"), Description: nil},
// 			},
// 			ChildMenus: []domain.ChildMenu{
// 				{
// 					OrderID:     1,
// 					Route:       StrPtr("/dev/features?tag=event"),
// 					Icon:        StrPtr("default-menu-events.svg"),
// 					Image:       nil,
// 					Template:    StrPtr("feature"),
// 					Description: StrPtr("Events"),
// 					Status:      "active",
// 					Translations: []domain.MenuTranslation{
// 						{LanguageID: 1, Title: "Events", Caption: nil, Description: nil},
// 						{LanguageID: 2, Title: "Event", Caption: nil, Description: nil},
// 					},
// 				},
// 				{
// 					OrderID:     2,
// 					Route:       StrPtr("/dev/features?tag=nearby"),
// 					Icon:        StrPtr("default-menu-nearby.svg"),
// 					Image:       nil,
// 					Template:    StrPtr("feature"),
// 					Description: StrPtr("Nearby"),
// 					Status:      "active",
// 					Translations: []domain.MenuTranslation{
// 						{
// 							LanguageID:  1,
// 							Title:       "Nearby",
// 							Caption:     StrPtr("Find cool places around the hotel, from places to eat to places to shop"),
// 							Description: nil,
// 						},
// 						{
// 							LanguageID:  2,
// 							Title:       "Jelajah Sekitar",
// 							Caption:     StrPtr("Cari tempat asik di sekitar hotel, mulai dari tempat makan hingga tempat belanja"),
// 							Description: nil,
// 						},
// 					},
// 				},
// 				{
// 					OrderID:     3,
// 					Route:       StrPtr("/dev/features?tag=promo"),
// 					Icon:        StrPtr("default-menu-promo.svg"),
// 					Image:       nil,
// 					Template:    StrPtr("feature"),
// 					Description: StrPtr("Promotion & Discount"),
// 					Status:      "active",
// 					Translations: []domain.MenuTranslation{
// 						{
// 							LanguageID:  1,
// 							Title:       "Promotion & Discount",
// 							Caption:     StrPtr("Find and enjoy attractive promotions and discounts offered by the hotel"),
// 							Description: nil,
// 						},
// 						{
// 							LanguageID:  2,
// 							Title:       "Promo & Diskon",
// 							Caption:     StrPtr("Temukan dan nikmati promo dan diskon menarik yang disajikan hotel"),
// 							Description: nil,
// 						},
// 					},
// 				},
// 				{
// 					OrderID:     4,
// 					Route:       StrPtr("/dev/features?tag=destination"),
// 					Icon:        StrPtr("default-menu-destinations.svg"),
// 					Image:       nil,
// 					Template:    StrPtr("feature"),
// 					Description: StrPtr("Tourist Destinations"),
// 					Status:      "active",
// 					Translations: []domain.MenuTranslation{
// 						{
// 							LanguageID:  1,
// 							Title:       "Tourist Destinations",
// 							Caption:     StrPtr("Search and find tourist attractions around the hotel. Create moments by visiting new places."),
// 							Description: nil,
// 						},
// 						{
// 							LanguageID:  2,
// 							Title:       "Destinasi Wisata",
// 							Caption:     StrPtr("Cari dan temukan tempat wisata di sekitar hotel. Buat momen dengan mengunjungi tempat baru."),
// 							Description: nil,
// 						},
// 					},
// 				},
// 			},
// 		},
// 		{
// 			OrderID:     4,
// 			Route:       nil,
// 			Icon:        StrPtr("default-menu-hotel-guides.svg"),
// 			Image:       nil,
// 			Template:    StrPtr("menu"),
// 			Description: StrPtr("Hotel guide"),
// 			Status:      "active",
// 			Translations: []domain.MenuTranslation{
// 				{LanguageID: 1, Title: "Hotel Guide", Caption: nil, Description: nil},
// 				{LanguageID: 2, Title: "Panduan Hotel", Caption: nil, Description: nil},
// 			},
// 			ChildMenus: []domain.ChildMenu{
// 				{
// 					OrderID:     1,
// 					Route:       StrPtr("/dev/features?tag=facility"),
// 					Icon:        StrPtr("default-menu-facility.svg"),
// 					Image:       nil,
// 					Template:    StrPtr("feature"),
// 					Description: StrPtr("Hotel Facilities"),
// 					Status:      "active",
// 					Translations: []domain.MenuTranslation{
// 						{
// 							LanguageID:  1,
// 							Title:       "Hotel Facilities",
// 							Caption:     StrPtr("Find information about the facilities you can enjoy at the hotel"),
// 							Description: nil,
// 						},
// 						{
// 							LanguageID:  2,
// 							Title:       "Fasilitas Hotel",
// 							Caption:     StrPtr("Temukan informasi seputar fasilitas yang bisa Anda nikmati di hotel"),
// 							Description: nil,
// 						},
// 					},
// 				},
// 				{
// 					OrderID:     2,
// 					Route:       StrPtr("/dev/features?tag=accommodation"),
// 					Icon:        StrPtr("default-menu-accommodation.svg"),
// 					Image:       nil,
// 					Template:    StrPtr("feature"),
// 					Description: StrPtr("Hotel Room"),
// 					Status:      "active",
// 					Translations: []domain.MenuTranslation{
// 						{
// 							LanguageID:  1,
// 							Title:       "Hotel Room",
// 							Caption:     StrPtr("Information about the types and pictures of rooms available at the hotel"),
// 							Description: nil,
// 						},
// 						{
// 							LanguageID:  2,
// 							Title:       "Kamar Hotel",
// 							Caption:     StrPtr("Informasi seputar tipe dan gambar kamar yang tersedia di hotel"),
// 							Description: nil,
// 						},
// 					},
// 				},
// 				{
// 					OrderID:     3,
// 					Route:       StrPtr("/dev/callcenter"),
// 					Icon:        StrPtr("default-menu-call-center.svg"),
// 					Image:       nil,
// 					Template:    StrPtr("callcenter"),
// 					Description: StrPtr("Call Center"),
// 					Status:      "active",
// 					Translations: []domain.MenuTranslation{
// 						{
// 							LanguageID:  1,
// 							Title:       "Call Center",
// 							Caption:     StrPtr("Information important numbers to contact during your stay"),
// 							Description: nil,
// 						},
// 						{
// 							LanguageID:  2,
// 							Title:       "Pusat Panggilan",
// 							Caption:     StrPtr("Informasi nomor penting yang dapat dihubungi selama menginap"),
// 							Description: nil,
// 						},
// 					},
// 				},
// 				{
// 					OrderID:     4,
// 					Route:       StrPtr("/dev/wifi"),
// 					Icon:        StrPtr("default-menu-wifi.svg"),
// 					Image:       nil,
// 					Template:    StrPtr("wifi"),
// 					Description: StrPtr("Internet / Wifi"),
// 					Status:      "active",
// 					Translations: []domain.MenuTranslation{
// 						{LanguageID: 1,
// 							Title:       "Internet / Wifi",
// 							Caption:     StrPtr("Internet access information for your convenience"),
// 							Description: nil,
// 						},
// 						{LanguageID: 2,
// 							Title:       "Wifi",
// 							Caption:     StrPtr("Informasi akses internet untuk kenyamanan Anda"),
// 							Description: nil,
// 						},
// 					},
// 				},
// 				{
// 					OrderID:     5,
// 					Route:       StrPtr("/dev/features?tag=safety_procedure"),
// 					Icon:        StrPtr("default-menu-safety-procedure.svg"),
// 					Image:       nil,
// 					Template:    StrPtr("feature"),
// 					Description: StrPtr("Safety Procedures"),
// 					Status:      "active",
// 					Translations: []domain.MenuTranslation{
// 						{
// 							LanguageID:  1,
// 							Title:       "Safety Procedures",
// 							Caption:     StrPtr("Information about safety procedures during your stay"),
// 							Description: nil,
// 						},
// 						{
// 							LanguageID:  2,
// 							Title:       "Prosedur Keselamatan",
// 							Caption:     StrPtr("Informasi tentang prosedur keselamatan selama menginap"),
// 							Description: nil,
// 						},
// 					},
// 				},
// 				{
// 					OrderID:     6,
// 					Route:       StrPtr("/dev/features?tag=amenity"),
// 					Icon:        StrPtr("default-menu-amenities.svg"),
// 					Image:       nil,
// 					Template:    StrPtr("feature"),
// 					Description: StrPtr("Amenities"),
// 					Status:      "active",
// 					Translations: []domain.MenuTranslation{
// 						{
// 							LanguageID:  1,
// 							Title:       "Amenities",
// 							Caption:     StrPtr("Information on additional services available during your stay"),
// 							Description: nil,
// 						},
// 						{
// 							LanguageID:  2,
// 							Title:       "Amenities",
// 							Caption:     StrPtr("Informasi layanan tambahan yang tersedia selama Anda menginap"),
// 							Description: nil,
// 						},
// 					},
// 				},
// 			},
// 		},
// 		{
// 			OrderID:     5,
// 			Route:       StrPtr("order/adm/items"),
// 			Icon:        StrPtr("default-menu-food-order.svg"),
// 			Image:       nil,
// 			Template:    StrPtr("order"),
// 			Description: StrPtr("Food Order"),
// 			Status:      "active",
// 			Translations: []domain.MenuTranslation{
// 				{LanguageID: 1, Title: "Food Order", Caption: StrPtr("Food Order"), Description: nil},
// 				{LanguageID: 2, Title: "Pesan Makanan", Caption: StrPtr("Pesan Makanan"), Description: nil},
// 			},
// 		},
// 		{
// 			OrderID:     6,
// 			Route:       StrPtr("/amenities"),
// 			Icon:        StrPtr("default-menu-amenities-order.svg"),
// 			Image:       nil,
// 			Template:    StrPtr("order"),
// 			Description: StrPtr("Amenities"),
// 			Status:      "active",
// 			Translations: []domain.MenuTranslation{
// 				{LanguageID: 1, Title: "Amenities", Caption: StrPtr("Amenities"), Description: nil},
// 				{LanguageID: 2, Title: "Pesan Fasilitas", Caption: StrPtr("Pesan Fasilitas"), Description: nil},
// 			},
// 		},
// 		{
// 			OrderID:     7,
// 			Route:       nil,
// 			Icon:        StrPtr("default-menu-apps.svg"),
// 			Image:       nil,
// 			Template:    StrPtr("app"),
// 			Description: StrPtr("App"),
// 			Status:      "active",
// 			Translations: []domain.MenuTranslation{
// 				{LanguageID: 1, Title: "Apps", Caption: nil, Description: nil},
// 				{LanguageID: 2, Title: "Aplikasi", Caption: nil, Description: nil},
// 			},
// 		},
// 		{
// 			OrderID:     8,
// 			Route:       nil,
// 			Icon:        StrPtr("default-menu-inbox.svg"),
// 			Image:       nil,
// 			Template:    StrPtr("inbox"),
// 			Description: StrPtr("Inbox"),
// 			Status:      "active",
// 			Translations: []domain.MenuTranslation{
// 				{LanguageID: 1, Title: "Inbox", Caption: nil, Description: nil},
// 				{LanguageID: 2, Title: "Kotak Masuk", Caption: nil, Description: nil},
// 			},
// 		},
// 	}
// )
