server:
  base_path: ""
  log_type: "json"
  log_level: "debug"
  http:
    port: "1360"
    prefork: false
    strict_routing: false
    case_sensitive: false
    body_limit: 108003328  # 104 * 1024 * 1024
    concurrency: 262144    # 256 * 1024
    timeout:
      read: 5
      write: 10
      idle: 120
    allows_origin: "*"
    asset_path: ""
    base_url: ""
    cache_static_ttl: 86400 # 24 * 60 * 60
  grpc_port: "54000"

postgresql:
  host: "localhost"
  port: "15432"
  database: "tourney_system"
  user: "root"
  password: "yourpassword"
  path_migrate: "file://migration"
  timezone: "UTC"
  set_max_open_conns: 0
  set_max_idle_conns: 2
  set_conn_max_idle_time: 0
  set_conn_max_lifetime: 0

jwt:
  expiration: 3600
  signing_method: "HS256"
  signature_key: "kmzway87aa"
  expiration_temp: 600

default_limit_query: 100

smtp:
  mail: "smtp.gmail.com"
  port: 25
  start_tls: 587
  tsl_or_ssl: 465
  email_sender: ""
  password: ""

host_url: ""
disable_email: true
